### ISSUE TITLE
Error, (in StringTools:-RegMatch) second argument must be a string |IdentifiabilityODE.mpl:481|

### ISSUE THREAD

**Issue by ghost** [pogudingleb/SIAN#2]
Whenever I use a parameter in the power or root of a parameter I get this error:

Error, (in StringTools:-RegMatch) second argument must be a string |IdentifiabilityODE.mpl:481|

Examples of this error:
```
sigma := [diff(x(t), t) = lambda0*x(t)*1/lambda0^(1/5) - k2*u(t)*x(t), y(t) = x(t)]
sigma := [diff(x(t), t) = lambda0*x(t)/lambda1^0.5 - k2*u(t)*x(t), y(t) = x(t)]
sigma := [diff(x(t), t) = lambda0*x(t)/lambda1^psi - k2*u(t)*x(t), y(t) = x(t)]
```

Any idea how to fix it?

**Comment by pogudingleb** [comment]
Dear @mahdiarsadeghi ,

Thank you for your message!
In general, the algorithm does not allow noninteger powers and powers being parameters (and I am not aware of any rigorously justified algorithm for global identifiabiity allowing this). However, in my experience, it is typically possible to rewrite a model a bit in order to use the algorithm and make a conclusion about the original model (for an example, see Section A.2 in  https://arxiv.org/pdf/1812.10180.pdf). If it is okay with you to send me your model, I will be happy to look at it and suggest such a rewriting (would be great to make this automatic but this is for future research).

**Comment by ghost** [comment]
@pogudingleb: Thanks for the immediate reply! Here is the model I am working on: 

`sigma := [diff(x(t), t) = lambda0*x(t)/(1 + (lambda0*x(t)/lambda1)^Psi)^(1/Psi) - k2*u(t)*x(t), y(t) = x(t)]`

Where Psi is generally a large number. We can assume Psi=5 to make it easier, but it doesn't solve the error.

**Comment by pogudingleb** [comment]
@mahdiarsadeghi , thank you for sharing the model!

The overall idea is to introduce new variables instead of non-rational function. The main trick is not to increase the dimension of the model while doing so (in some sense, to "trade" some of the parameters for initial conditions, see below).

In this case, we introduce:
```
z(t) = (lambda0 * x(t) / lambda1)^Psi
w(t) = lambda0 / (1 + z(t))^(1/Psi)
```
Then one arrives at the following rational ODE system
```
diff(x(t), t) = x(t) * w(t) - k2 * u(t) * x(t)
diff(z(t), t) = Psi * x'(t) * z(t) / x(t) = Psi * (x(t) * w(t) - k2 * u(t) * x(t)) * z(t) / x(t)
diff(w(t), t) = -1/Psi * w(t) / (1 + z(t)) * z'(t) = -(x(t) * w(t) - k2 * u(t) * x(t)) * z(t) * w(t) / (x(t) * (1 + z(t)))
y(t) = x(t)
```

Note that it may look like `lambda0` and `lambda1` have "disappeared" but they are now just hidden inside the initial conditions for the new functions:
```
z(0) = (lambda0 * x(0) / lambda1)^Psi
w(0) = lambda0 / (1 + z(0))^(1/Psi)
```

We can now run SIAN on the ODE system we have constructed. The result is that `Psi`, `k2`, `x(0)`, `z(0)`, and `w(0)` are globally identifiable.
Global identifiability of `z(0)`, `w(0)`, and `Psi` implies global identifiability for `lambda0`. And now from global identifiability of `z(0)` we also deduce that lambda1 is globally identifiable. Therefore, the original model is globally identifiable.
